// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeVentas.Persistence.Context;

#nullable disable

namespace SistemaDeVentas.Persistence.Migrations
{
    [DbContext(typeof(SalesDataWarehouseContext))]
    partial class SalesDataWarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCategory", b =>
                {
                    b.Property<int>("CategoryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryKey"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryKey");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("DimCategory", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCustomer", b =>
                {
                    b.Property<int>("CustomerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerKey"));

                    b.Property<int>("CustomerID_NaturalKey")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LocationKey")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerKey");

                    b.HasIndex("CustomerID_NaturalKey")
                        .IsUnique();

                    b.HasIndex("LocationKey");

                    b.ToTable("DimCustomer", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateKey"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("DayOfMonth")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("Quarter")
                        .HasColumnType("tinyint");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("DateKey");

                    b.ToTable("DimDate", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimLocation", b =>
                {
                    b.Property<int>("LocationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationKey"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationKey");

                    b.HasIndex("Country", "City")
                        .IsUnique();

                    b.ToTable("DimLocation", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimOrderStatus", b =>
                {
                    b.Property<int>("StatusKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusKey"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusKey");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("DimOrderStatus", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimProduct", b =>
                {
                    b.Property<int>("ProductKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductKey"));

                    b.Property<int?>("CategoryKey")
                        .HasColumnType("int");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductID_NaturalKey")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductKey");

                    b.HasIndex("CategoryKey");

                    b.HasIndex("ProductID_NaturalKey")
                        .IsUnique();

                    b.ToTable("DimProduct", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Facts.FactSales", b =>
                {
                    b.Property<long>("SalesKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalesKey"));

                    b.Property<int>("CustomerKey")
                        .HasColumnType("int");

                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<int?>("LocationKey")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductKey")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("StatusKey")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SalesKey");

                    b.HasIndex("CustomerKey");

                    b.HasIndex("DateKey");

                    b.HasIndex("LocationKey");

                    b.HasIndex("ProductKey");

                    b.HasIndex("StatusKey");

                    b.ToTable("FactSales", (string)null);
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCustomer", b =>
                {
                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimLocation", "Location")
                        .WithMany("Customers")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimProduct", b =>
                {
                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Facts.FactSales", b =>
                {
                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCustomer", "Customer")
                        .WithMany("FactSales")
                        .HasForeignKey("CustomerKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimDate", "Date")
                        .WithMany("FactSales")
                        .HasForeignKey("DateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimLocation", "Location")
                        .WithMany("FactSales")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimProduct", "Product")
                        .WithMany("FactSales")
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimOrderStatus", "Status")
                        .WithMany("FactSales")
                        .HasForeignKey("StatusKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Date");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimCustomer", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimDate", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimLocation", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimOrderStatus", b =>
                {
                    b.Navigation("FactSales");
                });

            modelBuilder.Entity("SistemaDeVentas.Persistence.Entities.DataWareHouse.Dimensions.DimProduct", b =>
                {
                    b.Navigation("FactSales");
                });
#pragma warning restore 612, 618
        }
    }
}
